USE Kolejnictwo_Hurtownia;

DROP TABLE IF EXISTS Freight_Car_Assignment_FT;
DROP TABLE IF EXISTS Transport_FT;
DROP TABLE IF EXISTS Freight_Car_DT;
DROP TABLE IF EXISTS Junk_DT;
DROP TABLE IF EXISTS Contract_DT_SCD2;
DROP TABLE IF EXISTS Station_DT;
DROP TABLE IF EXISTS Date_DT;
DROP TABLE IF EXISTS Locomotive_DT;